### ISSUE TITLE
Errors running STGCN, GMAN and STNorm

### ISSUE THREAD

**Issue by Dansheng** [zezhishao/BasicTS#14]
Thank you for providing an excellent easy-to-use library for spatial-temporal prediction. 

But I found some running errors and now report them to you.

- STGCN 
```KeyError: "No object named 'STGCN' found in 'Arch' registry!"```

- GraphWaveNet
```RuntimeError: Expected 2D (unbatched) or 3D (batched) input to conv1d, but got input of size: [64, 32, 307, 13]```

- STNorm
```RuntimeError: Expected 2D (unbatched) or 3D (batched) input to conv1d, but got input of size: [64, 32, 307, 13]```

The above errors can be reproduced using the PEMS04 dataset. 

Looking forward to your reply.

**Comment by Dansheng** [comment]
Thanks to the author for the update, here is another solution for fixing STGCN:
```@ARCH_REGISTRY.register(name='STGCN')```

**Comment by zezhishao** [comment]
Yes, thank you very much for reporting these errors to me. I have fixed the bug in STGCN.

However, I can't reproduce these errors in Graph WaveNet and STNorm. Here are my actions:
1. clone the BasicTS project `git clone https://github.com/zezhishao/BasicTS.git`
3. download the raw_data and put them in `datasets/`
4. run scripts to preprocess PEMS03 dataset `python /path/to/BasicTS/scripts/data_preparation/PEMS03/generate_training_data.py`
5. run the model, e.g., `easytrain -c basicts/options/STNorm/STNorm_PEMS03.py --gpus '0'`, `easytrain -c basicts/options/GraphWaveNet/GraphWaveNet_PEMS03.py --gpus '0'`.

It looks like they work fine on all datasets on my computer. Do you have more information about these models or any changes to the code?
Please feel free to contact me if you have any questions.

**Comment by Dansheng** [comment]
I followed your steps, but still have problems. Here are more details. 
Environment: ```pytorch     1.11.0      py3.7_cuda11.3_cudnn8.2.0_0```
Error Report: 
```
  File "/data/data/xxxx/ST/src/easytorch/launcher/launcher.py", line 93, in launch_training
    train_dist(cfg)
  File "/data/data/xxxx/ST/src/easytorch/launcher/launcher.py", line 56, in training_func
    raise e
  File "/data/data/xxxx/ST/src/easytorch/launcher/launcher.py", line 52, in training_func
    runner.train(cfg)
  File "/data/data/xxxx/ST/src/easytorch/core/runner.py", line 351, in train
    loss = self.train_iters(epoch, iter_index, data)
  File "/data/data/xxxx/ST/src/basicts/runners/short_mts_runner.py", line 186, in train_iters
    prediction, real_value = self.forward(data=data, epoch=epoch, iter_num=iter_num, train=True)
  File "/data/data/xxxx/ST/src/basicts/runners/GraphWaveNet_runner.py", line 54, in forward
    prediction_data = self.model(history_data=history_data)     # B, L, N, C
  File "/data/data/xxxx/anaconda3/envs/torch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/data/xxxx/ST/src/basicts/archs/GraphWaveNet_arch/GraphWaveNet_arch.py", line 188, in forward
    gate = self.gate_convs[i](residual)
  File "/data/data/xxxx/anaconda3/envs/torch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/data/xxxx/anaconda3/envs/torch/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 302, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/data/data/xxxx/anaconda3/envs/torch/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 299, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: Expected 2D (unbatched) or 3D (batched) input to conv1d, but got input of size: [64, 32, 358, 13]
```
*: "xxxx" is my name, please ignore it. 


Also, I check the code, and theoretically there should be this error. 
```nn.Conv1d``` expects a 3-dimensional input in the shape [batch_size, channels, seq_len] while you are using a 4-dimensional input with shape [batch_size, channels, num_nodes, time_steps].

Btw, could you provide your email address that you use regularly?

**Comment by zezhishao** [comment]
I think it should be caused by different versions of pytorch.
You can contact me via email `zezhishao@gmail.com`.

**Comment by Ethan1X** [comment]
> 

Hi, have you solved this problem?  I'm having the same problem.

**Comment by zezhishao** [comment]
Hi @Ethan1X ~ Thanks for your ideas, and this issue is indeed caused by the PyTorch version.
Although BasicTS itself does not have many requirements on the Pytorch version, some baselines may encounter compatibility issues in higher versions.
I would recommend you use versions `1.10.0` or `1.9.1`, which have been tested.
